project_name: "govizz"
builds:
  -
    binary: "govizz"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "darwin"
      - "freebsd"
      - "linux"
      - "windows"
    goarch:
      - "386"
      - "arm"
      - "arm64"
      - "amd64"
    ldflags:
      - -s
      - -w
      - -X "main.version={{.Version}}"
      - -X "main.commit={{.Commit}}"
      - -X "main.date={{.Date}}"
archives:
  - format_overrides:
      - goos: "windows"
        format: "zip"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-next"
changelog:
  skip: true
